# Site Settings
title: Naomi Schalken
url: 'https://naomischalken.github.io/'
#baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Naomi Schalken
tagline: Research Master's Student Methodology and Statistics
pic: website.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I am a Research Master’s student Methodology and Statistics at Utrecht University. Currently, I’m writing my master’s thesis at the department of Methodology and Statistics about ‘Longitudinal evaluation of expert priors with the Data Agreement Criterion’, and I expect to finish in June 2018. During my Master’s I did several extracurricular and research related activities, such as described below. My primary interests in the field of Methodology and Statistics are Bayesian Statistics, Structural Equation Modelling and Survey Methodology. Of course, I am interested in many more topics in this field! After I finish my Master’s, I would like to do a PhD, and develop myself as an academic researcher. 

#sidebar links
email: n.schalken@uu.nl
linkedin: naomi-schalken
github: NaomiSchalken
twitter: '@NaomiSchalken'
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
