# Site Settings
title: Naomi Schalken
url: 'https://naomischalken.github.io/'
#baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Naomi Schalken
tagline: Research Master's Student Methodology and Statistics
pic: website.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: About me 

#sidebar links
email: n.schalken@uu.nl
linkedin: naomi-schalken-3152a8b8
github: NaomiSchalken
twitter: '@NaomiSchalken'
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
